name = "MorePolynomials"
uuid = "4c225ef1-f68b-4b9a-b09e-b75007f139f2"
authors = ["Nathan Davey"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
